#!/bin/bash
apt-get update && apt-get clean

#setup maven
apt-get install -y maven

#install git
apt-get install -y git

#install java
apt-get install -y openjdk-7-jdk

#build the project
git clone https://gitlab.com/qatraining/qadockerint-hello-scalatra

cd hello-scalatra

mvn package
mvn jetty:run
