#!/bin/bash
apt-get update && apt-get clean

#setup maven
apt-get install -y maven

#install git
apt-get install -y git

#install java
apt-get install -y openjdk-8-jdk openjdk-8-jre-headless

#build the project
git clone https://bitbucket.org/qadevopsmast/hello-scalatra hello-scalatra

cd hello-scalatra

mvn package
mvn jetty:run
